services:
    magazneto_user.registration.form.type:
        class: Magazento\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: magazento_user_registration }
    magazneto_user.profile.form.type:
        class: Magazento\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: magazento_user_profile }
            