<?php

namespace Magazento\BillingBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * HistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryRepository extends DocumentRepository
{
    
    public function getLast($userId) {
        return $this->createQueryBuilder()
                        ->field('user_id')->equals($userId)
                        ->sort('id', 'DSC')
                        ->limit(1)
                        ->getQuery()
                        ->execute()
                        ->getSingleResult();
    }    
    
    public function removeByUserId($userId) {
        return $this->createQueryBuilder()
                        ->remove()
                        ->field('user_id')->equals($userId)
                        ->getQuery()
                        ->execute();
    }    
    
    
    public function getHistoryByUserId($userId) {

        $entry = $this->createQueryBuilder()
                ->field('user_id')->equals($userId)
                ->sort('time', 'DSC')                
                ->getQuery()
                ->execute()->toArray();
        
        $data= array();
        $i=0;
        foreach ($entry as $_entry) {
            $data[$i]['id'] = $_entry->getId();
            $data[$i]['status'] = $_entry->getStatus();
            $data[$i]['amount'] = $_entry->getAmount() . ' USD';
            $data[$i]['time'] = date("F j, Y, g:i a",$_entry->getTime()->__toString());
            $i++;
        }
        
        return $data;
    }

    
}