<?php

namespace Magazento\SettingsBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * MailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailRepository extends DocumentRepository
{
}