magazento_service:
    resource: "@MagazentoServiceBundle/Controller/"
    type:     annotation
    prefix:   /

magazento_api:
    resource: "@MagazentoApiBundle/Controller/"
    type:     annotation
    prefix:   /

magazento_settings:
    resource: "@MagazentoSettingsBundle/Controller/"
    type:     annotation
    prefix:   /

magazento_admin:
    resource: "@MagazentoAdminBundle/Controller/"
    type:     annotation
    prefix:   /
magazento_console:
    resource: "@MagazentoConsoleBundle/Controller/"
    type:     annotation
    prefix:   /
magazento_billing:
    resource: "@MagazentoBillingBundle/Controller/"
    type:     annotation
    prefix:   /
magazento_build:
    resource: "@MagazentoBuildBundle/Controller/"
    type:     annotation
    prefix:   /
magazento_menu:
    resource: "@MagazentoMenuBundle/Controller/"
    type:     annotation
    prefix:   /
magazento_user:
    resource: "@MagazentoUserBundle/Controller/"
    type:     annotation
    prefix:   /
magazento_catalog:
    resource: "@MagazentoCatalogBundle/Controller/"
    type:     annotation
    prefix:   /
    
    
#ALL
_magazento_homepage:
    pattern:  /
    defaults: { _controller: MagazentoMenuBundle:Default:homepage }    
_magazento_howitworks:
    pattern:  /howitworks
    defaults: { _controller: MagazentoMenuBundle:Default:howitworks }    
_magazento_why:
    pattern:  /whywe
    defaults: { _controller: MagazentoMenuBundle:Default:why }    
_magazento_start:
    pattern:  /start
    defaults: { _controller: MagazentoMenuBundle:Default:start }    
_magazento_pricing:
    pattern:  /pricing
    defaults: { _controller: MagazentoMenuBundle:Default:pricing }    
_magazento_contact:
    pattern:  /contact
    defaults: { _controller: MagazentoMenuBundle:Default:contact }    
_magazento_demo_iphone:
    pattern:  /demo/iphone
    defaults: { _controller: MagazentoMenuBundle:Default:demoiphone }    
_magazento_demo_android:
    pattern:  /demo/android
    defaults: { _controller: MagazentoMenuBundle:Default:demoandroid }    
    
#Billing
_magazento_billing_changeplan:
    pattern:  /billing/changeplan
    defaults: { _controller: MagazentoBillingBundle:Default:changeplan }    
_magazento_billing_pay:
    pattern:  /billing/pay
    defaults: { _controller: MagazentoBillingBundle:Default:pay }    
_magazento_billing_index:
    pattern:  /billing
    defaults: { _controller: MagazentoBillingBundle:Default:index }    

  
#Build
_magazento_build:    
    pattern:  /build
    defaults: { _controller: MagazentoBuildBundle:Build:build } 
_magazento_build_run:    
    pattern:  /build/iphone
    defaults: { _controller: MagazentoBuildBundle:Build:buildIphone }  
_magazento_build_download_iphone:    
    pattern:  /build/iphone/download
    defaults: { _controller: MagazentoBuildBundle:Build:downloadIphone }  
      
    
#Profile
_magazento_settings:    
    pattern:  /settings
    defaults: { _controller: MagazentoSettingsBundle:Default:settings }       
_magazento_settings_apple:    
    pattern:  /settings/apple
    defaults: { _controller: MagazentoSettingsBundle:Default:apple }   
        
    


    
#Billing   
_magazento_billing:
    pattern:  /billing
    defaults: { _controller: MagazentoBillingBundle:Default:index }    
_magazento_billing_change_plan:
    pattern:  /billing/planchange
    defaults: { _controller: MagazentoBillingBundle:Default:planChange }   
_magazento_billing_payment_send:
    pattern:  /billing/send
    defaults: { _controller: MagazentoBillingBundle:Payment:send }    
_magazento_billing_payment_success:
    pattern:  /billing/success
    defaults: { _controller: MagazentoBillingBundle:Payment:success }    
    
  #Catalog   
_magazento_catalog_upload:
    pattern:  /catalog/upload
    defaults: { _controller: MagazentoCatalogBundle:Default:upload }    
_magazento_catalog:
    pattern:  /catalog/productgrid
    defaults: { _controller: MagazentoCatalogBundle:Default:productgrid }       
_magazento_catalog_productgrid:
    pattern:  /catalog/productgrid
    defaults: { _controller: MagazentoCatalogBundle:Default:productgrid }    
_magazento_catalog_categoryjson:
    pattern:  /catalog/category/json
    defaults: { _controller: MagazentoCatalogBundle:Default:categoryJSON }  
_magazento_catalog_categorygrid:
    pattern:  /catalog/categorygrid
    defaults: { _controller: MagazentoCatalogBundle:Default:categorygrid }     
    
#_grid_category_delete:    
#    pattern:  /catalog/categorygrid/delete
#    defaults: { _controller: MagazentoCatalogBundle:Default:categoryGridDelete }   
#_grid_product_delete:    
#    pattern:  /catalog/productgrid/delete
#    defaults: { _controller: MagazentoCatalogBundle:Default:productGridDelete }   


#Upload    
_magazento_catalog_upload:
    pattern:  /catalog/upload/
    defaults: { _controller: MagazentoCatalogBundle:Default:upload } 

#FOS User
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
    pattern:  /profile    

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
    
#ADMIN
_admin_login:
    pattern:   /admin/login
    defaults:  { _controller: MagazentoAdminBundle:Security:login }
    
_admin_history:
    pattern:   /admin/history
    defaults:  { _controller: MagazentoAdminBundle:History:history }    
    
_admin_user:
    pattern:   /admin/user
    defaults:  { _controller: MagazentoAdminBundle:User:user }   
    
_admin_user_delete:
    pattern:   /admin/user/delete
    defaults:  { _controller: MagazentoAdminBundle:User:userdelete }        
    
_admin_logout:
    pattern:   /admin/logout
    
_admin_login_check:
    pattern:   /admin/login_check