security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    admin: { password: admin12qw12, roles: 'ROLE_ADMIN' }            

    firewalls:
        admin_secured:
            pattern: ^/admin
            anonymous: ~
            provider: in_memory
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check
                default_target_path: /admin/user 
            logout:
                path:   /admin/logout
                target: /admin/login                
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /build
            logout:       true
            anonymous:    true
     

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /catalog*, role: IS_AUTHENTICATED_FULLY }
        - { path: /settings*, role: IS_AUTHENTICATED_FULLY }
        - { path: /build*, role: IS_AUTHENTICATED_FULLY }
        - { path: /billing*, role: IS_AUTHENTICATED_FULLY }
        
        - { path: /admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /admin/*, role: ROLE_ADMIN }
