<?php

namespace MongoDBODMProxies\__CG__\Magazento\SettingsBundle\Document;

use Doctrine\ODM\MongoDB\Persisters\DocumentPersister;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class Apple extends \Magazento\SettingsBundle\Document\Apple implements \Doctrine\ODM\MongoDB\Proxy\Proxy
{
    private $__documentPersister__;
    public $__identifier__;
    public $__isInitialized__ = false;
    public function __construct(DocumentPersister $documentPersister, $identifier)
    {
        $this->__documentPersister__ = $documentPersister;
        $this->__identifier__ = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->__documentPersister__) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->__documentPersister__->load($this->__identifier__, $this) === null) {
                throw \Doctrine\ODM\MongoDB\DocumentNotFoundException::documentNotFound(get_class($this), $this->__identifier__);
            }
            unset($this->__documentPersister__, $this->__identifier__);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return $this->__identifier__;
        }
        $this->__load();
        return parent::getId();
    }

    public function setUserId($userId)
    {
        $this->__load();
        return parent::setUserId($userId);
    }

    public function getUserId()
    {
        $this->__load();
        return parent::getUserId();
    }

    public function setP12($p12)
    {
        $this->__load();
        return parent::setP12($p12);
    }

    public function getP12()
    {
        $this->__load();
        return parent::getP12();
    }

    public function setMobileprovision($mobileprovision)
    {
        $this->__load();
        return parent::setMobileprovision($mobileprovision);
    }

    public function getMobileprovision()
    {
        $this->__load();
        return parent::getMobileprovision();
    }

    public function setPasswordDev($passwordDev)
    {
        $this->__load();
        return parent::setPasswordDev($passwordDev);
    }

    public function getPasswordDev()
    {
        $this->__load();
        return parent::getPasswordDev();
    }

    public function setPasswordProd($passwordProd)
    {
        $this->__load();
        return parent::setPasswordProd($passwordProd);
    }

    public function getPasswordProd()
    {
        $this->__load();
        return parent::getPasswordProd();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'user_id', 'password_dev', 'password_prod', 'p12', 'mobileprovision');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->__documentPersister__) {
            $this->__isInitialized__ = true;
            $class = $this->__documentPersister__->getClassMetadata();
            $original = $this->__documentPersister__->load($this->__identifier__);
            if ($original === null) {
                throw \Doctrine\ODM\MongoDB\MongoDBException::documentNotFound(get_class($this), $this->__identifier__);
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->__documentPersister__, $this->__identifier__);
        }
        
    }
}