<?php

namespace Magazento\BuildBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * BuildHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildHistoryRepository extends DocumentRepository
{

    public function getLast($userId,$type) {
        return $this->createQueryBuilder()
                        ->field('user_id')->equals($userId)
                        ->field('type')->equals($type)
                        ->sort('log_time', 'DSC')
                        ->limit(1)
                        ->getQuery()
                        ->execute()
                        ->getSingleResult();
    }
    
    public function removeByUserId($userId) {
        return $this->createQueryBuilder()
                        ->remove()
                        ->field('user_id')->equals($userId)
                        ->getQuery()
                        ->execute();
    }
        
    public function getAllHistory() {

        $history = $this->createQueryBuilder()
                ->getQuery()
                ->execute();
                
        
        $data= array();
        $i=0;
        foreach ($history as $_log) {
            $data[$i]['id'] = $_log->getId();
            $data[$i]['user_id'] = $_log->getUserId();
            $data[$i]['log_rawtime'] = $_log->getLogTime()->__toString();
            $data[$i]['log_time'] = date("F j, Y, g:i a",$_log->getLogTime()->__toString());
            $data[$i]['type'] = $_log->getType();
            $data[$i]['log'] = $_log->getLog();
            $i++;
        }
        
        
        return $data;
    }    
}