<?php

namespace Magazento\BuildBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class BuildController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Magazento\BuildBundle\Controller\BuildController();
        return $instance;
    }
}
