<?php

namespace Magazento\CatalogBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends DocumentRepository {

    public function removeByUserId($userId) {
        return $this->createQueryBuilder()
                        ->remove()
                        ->field('user_id')->equals($userId)
                        ->getQuery()
                        ->execute();
    }
    
    public function massRemove($ids) {
        foreach ($ids as $id) {
            $this->createQueryBuilder()
                            ->remove()
                            ->field('id')->equals($id)
                            ->getQuery()
                            ->execute();            
        }
    }    
    
    public function getCategoriesByUserId($userId) {

        $categories = $this->createQueryBuilder()
                ->field('user_id')->equals($userId)
                ->getQuery()
                ->execute()->toArray();
        
        $data= array();
        $i=0;
        foreach ($categories as $_category) {
            $data[$i]['id'] = $_category->getXmlCategoryId();
            $data[$i]['parentId'] = $_category->getXmlParentId();
            $data[$i]['name'] = $_category->getName();
            $i++;
        }
        
        
        return $data;
    }
}